title: "Sam Chakraborty MSc. "
description: "Researcher @Shanghai Jiao Tong University"
url: "https://samsomyajit.github.io"
author: "Sam Chakraborty"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sass-converter
  - jekyll-sitemap
math_engine: mathjax
